main.py: fix typo in TFLOW_SUBS
This is causing problems for me:

```
PackagesNotFoundError: The following packages are not available from current channels:

  - pkgs/main/linux-64::tensorflow==1.8.0=h7b2774c_0 -> _tflow_select==1.2.0=eigen

```